Data Structure

In [108]:
import pandas as pd
import numpy as np

In [109]:
#Creating Data structures
s = pd.Series(np.random.randn(5), index=['A', 'B', 'C', 'D', 'E'])
s

A   -1.989683
B    0.820496
C   -1.466282
D   -1.562445
E    1.325341
dtype: float64

In [110]:
s.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [111]:
a = pd.Series(np.random.randn(10))
a

0   -1.160148
1   -1.204139
2   -0.496282
3    1.785130
4   -1.147066
5    1.116241
6   -1.189074
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [112]:
#Creating through dictionaries
d = {'a':11.0, 'b': 22.0, 'C': 33.0, 'd': 44.0}
d

{'a': 11.0, 'b': 22.0, 'C': 33.0, 'd': 44.0}

In [113]:
pd.Series(d)

a    11.0
b    22.0
C    33.0
d    44.0
dtype: float64

In [114]:
pd.Series(d, index=['b', 'c', 'd', 'a', 'e'])
d

{'a': 11.0, 'b': 22.0, 'C': 33.0, 'd': 44.0}

In [115]:
pd.Series(5.0, index=['a', 'b', 'c', 'd', 'e']) #Generates same data

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

In [116]:
a

0   -1.160148
1   -1.204139
2   -0.496282
3    1.785130
4   -1.147066
5    1.116241
6   -1.189074
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [117]:
#Series in ndarry-like
a.iloc[0]

-1.1601482707017388

In [118]:
a.iloc[2]

-0.49628217451577133

In [119]:
a.iloc[5]

1.1162407423849263

In [120]:
a.iloc[:]

0   -1.160148
1   -1.204139
2   -0.496282
3    1.785130
4   -1.147066
5    1.116241
6   -1.189074
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [121]:
a.iloc[1:3]

1   -1.204139
2   -0.496282
dtype: float64

In [122]:
a.iloc[2:10]

2   -0.496282
3    1.785130
4   -1.147066
5    1.116241
6   -1.189074
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [123]:
a.median()

-0.2321833678132609

In [124]:
a[a>a.median()]

3    1.785130
5    1.116241
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [125]:
a.iloc[[0, 3, 5, 7]]

0   -1.160148
3    1.785130
5    1.116241
7    1.070607
dtype: float64

In [126]:
np.exp(a)

0     0.313440
1     0.299950
2     0.608790
3     5.960357
4     0.317567
5     3.053354
6     0.304503
7     2.917148
8    13.760406
9     1.032430
dtype: float64

In [127]:
a.dtype

dtype('float64')

In [128]:
a.array

<NumpyExtensionArray>
[ -1.1601482707017388,  -1.2041389660996265, -0.49628217451577133,
    1.785130429763423,  -1.1470658674549201,   1.1162407423849263,
  -1.1890744001903408,   1.0706065218896526,    2.621795333105346,
  0.03191543888924953]
Length: 10, dtype: float64

In [129]:
a.to_numpy()

array([-1.16014827, -1.20413897, -0.49628217,  1.78513043, -1.14706587,
        1.11624074, -1.1890744 ,  1.07060652,  2.62179533,  0.03191544])

In [130]:
a

0   -1.160148
1   -1.204139
2   -0.496282
3    1.785130
4   -1.147066
5    1.116241
6   -1.189074
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [131]:
a.to_numpy() #Changing into numpy array

array([-1.16014827, -1.20413897, -0.49628217,  1.78513043, -1.14706587,
        1.11624074, -1.1890744 ,  1.07060652,  2.62179533,  0.03191544])

In [132]:
s

A   -1.989683
B    0.820496
C   -1.466282
D   -1.562445
E    1.325341
dtype: float64

In [133]:
s['A']

-1.9896825249712113

In [134]:
s['D']

-1.5624450695465992

In [135]:
#Get Functions
a.get('A', np.nan)

nan

In [136]:
a

0   -1.160148
1   -1.204139
2   -0.496282
3    1.785130
4   -1.147066
5    1.116241
6   -1.189074
7    1.070607
8    2.621795
9    0.031915
dtype: float64

In [137]:
b = pd.Series(np.random.rand(10))
b

0    0.009209
1    0.979811
2    0.083158
3    0.586980
4    0.020006
5    0.821774
6    0.657718
7    0.762026
8    0.785442
9    0.781813
dtype: float64

In [138]:
a + b

0   -1.150939
1   -0.224328
2   -0.413124
3    2.372111
4   -1.127060
5    1.938015
6   -0.531356
7    1.832632
8    3.407238
9    0.813728
dtype: float64

In [139]:
a*b

0   -0.010684
1   -1.179828
2   -0.041270
3    1.047837
4   -0.022948
5    0.917297
6   -0.782076
7    0.815830
8    2.059269
9    0.024952
dtype: float64

In [140]:
a-b

0   -1.169358
1   -2.183950
2   -0.579441
3    1.198150
4   -1.167072
5    0.294467
6   -1.846793
7    0.308581
8    1.836353
9   -0.749897
dtype: float64

In [141]:
a/b

0   -125.974416
1     -1.228951
2     -5.967916
3      3.041209
4    -57.336848
5      1.358331
6     -1.807878
7      1.404948
8      3.337986
9      0.040822
dtype: float64

In [142]:
a**2

0    1.345944
1    1.449951
2    0.246296
3    3.186691
4    1.315760
5    1.245993
6    1.413898
7    1.146198
8    6.873811
9    0.001019
dtype: float64

In [143]:
#Creating a DataFrame
d = {
    "A":pd.Series([11, 22, 33, 44, 55], index = [1, 2, 3, 4, 5]),
    "B":pd.Series([111, 222, 333, 444, 555], index = [1, 2, 3, 4, 5])
}
df = pd.DataFrame(d)
df

A    B
1  11  111
2  22  222
3  33  333
4  44  444
5  55  555

In [147]:
a = pd.DataFrame({
    "A":[1, 2, 3, 4, 5], 
    "B":[33, 54, 55, 454, 2343]
})
a

A     B
0  1    33
1  2    54
2  3    55
3  4   454
4  5  2343

In [149]:
a

A     B
0  1    33
1  2    54
2  3    55
3  4   454
4  5  2343

In [150]:
df

A    B
1  33  111
2  33  222
3  33  333
4  33  444
5  33  555

In [151]:
data = np.zeros(3)

In [152]:
data

array([0., 0., 0.])

In [161]:
df.query("B>300")

A    B
3  33  333
4  33  444
5  33  555

In [163]:
idx = pd.Index(np.arange(10))
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')

In [165]:
df.sum(0, skipna=True)

A     165
B    1665
dtype: int64

In [166]:
df

A    B
1  33  111
2  33  222
3  33  333
4  33  444
5  33  555

In [168]:
df1 = pd.DataFrame(np.random.randn(100, 4),
                   columns=list('ABCD'),
                   index=pd.date_range("20230101", periods=100))
df1

A         B         C         D
2023-01-01 -0.099492  0.041223  0.326294 -0.735678
2023-01-02  0.144425  0.814132 -1.372340  0.206552
2023-01-03  0.341804  0.797397 -0.305666  0.282299
2023-01-04 -1.510826 -0.209768 -0.745931  1.061330
2023-01-05 -0.449483 -0.772233 -0.382787 -0.768594
...              ...       ...       ...       ...
2023-04-06 -0.672194 -0.413014 -0.235989 -0.045640
2023-04-07 -0.485760  0.594956  0.189292  1.099412
2023-04-08  1.417293 -1.798883  0.749775  0.098239
2023-04-09  0.911300  0.338012 -1.214245  0.704153
2023-04-10 -0.636853  0.400156  0.222446  0.405984

[100 rows x 4 columns]

In [169]:
df1.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [171]:
df1.sum(0, skipna=False)

A    -6.214526
B     2.660862
C   -24.944413
D     7.360125
dtype: float64

In [173]:
df1.loc["2023-01-01":"2023-01-05"]

A         B         C         D
2023-01-01 -0.099492  0.041223  0.326294 -0.735678
2023-01-02  0.144425  0.814132 -1.372340  0.206552
2023-01-03  0.341804  0.797397 -0.305666  0.282299
2023-01-04 -1.510826 -0.209768 -0.745931  1.061330
2023-01-05 -0.449483 -0.772233 -0.382787 -0.768594

In [184]:
df1.loc[df1['A']>0.9]

A         B         C         D
2023-01-13  0.966036  1.500642  2.773600  0.175904
2023-01-18  1.178569 -0.145889 -1.457386 -1.286832
2023-01-28  1.554668 -1.264565 -1.950390  0.684095
2023-02-12  0.922884 -0.974392 -0.889681  1.240900
2023-02-16  2.235034 -0.456826 -2.605627 -1.482658
2023-02-17  1.376450  1.203813  0.571679  0.166275
2023-02-25  1.441330 -0.111319  1.460460 -1.540510
2023-02-26  1.584722  0.405122  0.641553 -2.263599
2023-03-19  2.526156  0.092811  1.816525 -1.172391
2023-03-22  1.352096  1.277883  0.076621  1.380980
2023-03-23  1.017165  0.548945 -1.386809 -0.769277
2023-03-25  1.110070 -0.976168 -1.237554  0.507719
2023-03-27  1.444534 -0.361479 -0.835303  0.674527
2023-04-08  1.417293 -1.798883  0.749775  0.098239
2023-04-09  0.911300  0.338012 -1.214245  0.704153

In [185]:
df1.loc[df1['B']>0.9]

A         B         C         D
2023-01-07 -0.353972  2.950212  0.867890 -0.381308
2023-01-13  0.966036  1.500642  2.773600  0.175904
2023-01-20 -0.120900  2.120664 -0.776215 -0.568314
2023-01-24 -0.126214  1.062853 -0.460593  0.126704
2023-01-27  0.465786  2.475747 -1.009007 -0.773947
2023-02-10 -1.249578  1.965699  0.087204  0.513044
2023-02-11  0.524472  1.926718 -0.869045  0.934969
2023-02-13 -0.474765  1.745003 -1.344110  0.946546
2023-02-15  0.401722  1.408239 -1.603235 -0.656103
2023-02-17  1.376450  1.203813  0.571679  0.166275
2023-02-24 -0.341519  0.994199 -2.167798  0.144335
2023-02-27 -0.021950  0.951912  0.339829  1.175724
2023-03-15  0.468739  1.262099  0.464018  0.580963
2023-03-16  0.304914  0.941583 -0.248672  0.471084
2023-03-17  0.531371  0.947959 -0.027637 -0.230212
2023-03-22  1.352096  1.277883  0.076621  1.380980
2023-03-26 -1.203763  1.032355  1.057079  2.088848
2023-04-03  0.122823  1.197614 -1.637993 -0.468783
2023-04-05 -0.285288  1.611720 -0.833896  0.297218

In [186]:
df1.loc[df1['C']>0.9]

A         B         C         D
2023-01-09  0.657235 -0.719583  1.740565 -0.245770
2023-01-11  0.459950  0.768001  1.329530 -0.008924
2023-01-13  0.966036  1.500642  2.773600  0.175904
2023-01-30 -1.173687 -1.067359  1.858553 -1.399704
2023-01-31 -0.073176 -0.254697  1.808426 -1.180992
2023-02-01  0.243577  0.418322  1.152808 -0.710099
2023-02-03 -2.294819  0.382227  1.108119 -0.461634
2023-02-08 -0.154289 -0.433926  0.994986 -0.306108
2023-02-25  1.441330 -0.111319  1.460460 -1.540510
2023-03-19  2.526156  0.092811  1.816525 -1.172391
2023-03-26 -1.203763  1.032355  1.057079  2.088848

In [187]:
df1.loc[df1['D']>0.9]

A         B         C         D
2023-01-04 -1.510826 -0.209768 -0.745931  1.061330
2023-01-22 -0.487490 -0.290270 -0.300457  0.922894
2023-01-23  0.583497  0.367751 -2.425995  1.172072
2023-01-26 -2.131603 -1.959836  0.823166  0.964956
2023-02-04 -0.370455  0.573513  0.740937  2.255042
2023-02-11  0.524472  1.926718 -0.869045  0.934969
2023-02-12  0.922884 -0.974392 -0.889681  1.240900
2023-02-13 -0.474765  1.745003 -1.344110  0.946546
2023-02-20 -1.281137 -0.640040  0.661411  1.797900
2023-02-22 -3.153068 -0.713135 -0.454650  1.101051
2023-02-27 -0.021950  0.951912  0.339829  1.175724
2023-03-02  0.270333  0.412512 -0.573261  1.459522
2023-03-06 -0.041217  0.788784 -1.110142  1.854996
2023-03-08  0.396875 -0.795234  0.440779  1.019876
2023-03-11  0.038895  0.050404 -0.073205  1.154940
2023-03-12 -1.295236  0.473244  0.777336  1.224203
2023-03-22  1.352096  1.277883  0.076621  1.380980
2023-03-26 -1.203763  1.032355  1.057079  2.088848
2023-04-04 -1.454140 -0.836532 -0.831738  2.404370
2023-04-07 -0.485760  0.594956  0.189292  1.099412